version: '3.5'

services:
  websocket:
    image: "namson0482/websocket-frontend:1.0"
    container_name: "websocket-frontend-container"
    ports:
      - "7070:80"
    networks:
      static-network:
        ipv4_address: 10.5.0.6

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
