server:
    port: 8082
spring:
    kafka:
        consumer:
            bootstrap-servers: websocket:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            group-id: "group_id"

    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: password

topic:
    name: t.food.order
