version: '3.5'

services:
  websocket_consumer:
      image: "namson0482/kafka-websocket-consumer:1.0"
      container_name: "kafka-websocket-consumer-container"
      ports:
        - "8082:8082" #<Computer_port>:<Container_port>
# Uncomment code below if you want to mount local directory to container directory
#      volumes:
#        - type: bind
#          source: /Users/macbook/Documents/Docs/Tasks/stored # Folder archive the raw files
#          target: /temp/
      environment:
        SPRING_PROFILES_ACTIVE: "docker-env"
        DATA_FILE: "/temp/"
