version: '3.5'

services:
  websocket_consumer:
      image: "namson0482/kafka-websocket-consumer:1.0"
      container_name: "kafka-websocket-consumer-container"
      ports:
        - "8082:8082" #<Computer_port>:<Container_port>
      environment:
        SPRING_PROFILES_ACTIVE: "docker-env"
